"""kenya_schema_evolution

Revision ID: 7af45e7fc361
Revises: 82a4d92f63d4
Create Date: 2026-02-14 20:34:03.588714

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7af45e7fc361"
down_revision: Union[str, Sequence[str], None] = "82a4d92f63d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ownership_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("owner_name", sa.String(length=255), nullable=False),
        sa.Column("nationality", sa.String(length=100), nullable=True),
        sa.Column("postal_address", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ownership_company", "ownership_records", ["company_id"], unique=False
    )
    op.create_index(
        "ix_ownership_name", "ownership_records", ["owner_name"], unique=False
    )
    op.create_table(
        "contracts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tender_id", sa.UUID(), nullable=True),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("contract_number", sa.String(length=100), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("contract_amount", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("date_signed", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("procurement_method", sa.String(length=100), nullable=True),
        sa.Column("procurement_category", sa.String(length=100), nullable=True),
        sa.Column("agpo_group", sa.String(length=50), nullable=True),
        sa.Column("reservation_group", sa.String(length=50), nullable=True),
        sa.Column("is_agpo_reserved", sa.Boolean(), nullable=True),
        sa.Column("pe_name", sa.String(length=255), nullable=True),
        sa.Column("pe_type", sa.String(length=100), nullable=True),
        sa.Column("source_system", sa.String(length=20), nullable=True),
        sa.Column("source_record_id", sa.String(length=255), nullable=True),
        sa.Column("ingested_at", sa.DateTime(), nullable=True),
        sa.Column("data_quality_flags", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tender_id"], ["tenders.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contract_number"),
    )
    op.create_index("ix_contracts_company", "contracts", ["company_id"], unique=False)
    op.create_index("ix_contracts_source", "contracts", ["source_system"], unique=False)
    op.create_index("ix_contracts_tender", "contracts", ["tender_id"], unique=False)
    op.add_column(
        "companies", sa.Column("supplier_type", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "companies", sa.Column("brs_number", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "companies",
        sa.Column("egp_registration_number", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "companies", sa.Column("contact_email", sa.String(length=255), nullable=True)
    )
    op.add_column("companies", sa.Column("physical_address", sa.Text(), nullable=True))
    op.add_column("companies", sa.Column("postal_address", sa.Text(), nullable=True))
    op.add_column(
        "companies", sa.Column("postal_code", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "companies", sa.Column("source_system", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "companies", sa.Column("source_record_id", sa.String(length=100), nullable=True)
    )
    op.add_column("companies", sa.Column("ingested_at", sa.DateTime(), nullable=True))
    op.add_column(
        "companies", sa.Column("data_quality_flags", sa.JSON(), nullable=True)
    )
    op.alter_column(
        "companies", "registration_date", existing_type=sa.DATE(), nullable=True
    )
    op.alter_column("companies", "address", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "companies", "phone", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.add_column(
        "tenders", sa.Column("procurement_method", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "tenders",
        sa.Column("procurement_category", sa.String(length=100), nullable=True),
    )
    op.add_column("tenders", sa.Column("pe_type", sa.String(length=100), nullable=True))
    op.add_column(
        "tenders",
        sa.Column(
            "currency", sa.String(length=10), nullable=False, server_default="KES"
        ),
    )
    op.add_column("tenders", sa.Column("ocds_id", sa.String(length=255), nullable=True))
    op.add_column("tenders", sa.Column("buyer_id", sa.String(length=50), nullable=True))
    op.add_column(
        "tenders", sa.Column("source_system", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "tenders", sa.Column("source_record_id", sa.String(length=255), nullable=True)
    )
    op.add_column("tenders", sa.Column("ingested_at", sa.DateTime(), nullable=True))
    op.add_column("tenders", sa.Column("data_quality_flags", sa.JSON(), nullable=True))
    op.alter_column(
        "tenders",
        "reference_number",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "tenders",
        "estimated_value",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column("tenders", "published_date", existing_type=sa.DATE(), nullable=True)
    op.alter_column("tenders", "deadline", existing_type=sa.DATE(), nullable=True)
    op.create_index("ix_tenders_source", "tenders", ["source_system"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tenders_source", table_name="tenders")
    op.alter_column("tenders", "deadline", existing_type=sa.DATE(), nullable=False)
    op.alter_column(
        "tenders", "published_date", existing_type=sa.DATE(), nullable=False
    )
    op.alter_column(
        "tenders",
        "estimated_value",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "tenders",
        "reference_number",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.drop_column("tenders", "data_quality_flags")
    op.drop_column("tenders", "ingested_at")
    op.drop_column("tenders", "source_record_id")
    op.drop_column("tenders", "source_system")
    op.drop_column("tenders", "buyer_id")
    op.drop_column("tenders", "ocds_id")
    op.drop_column("tenders", "currency")
    op.drop_column("tenders", "pe_type")
    op.drop_column("tenders", "procurement_category")
    op.drop_column("tenders", "procurement_method")
    op.alter_column(
        "companies", "phone", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column("companies", "address", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "companies", "registration_date", existing_type=sa.DATE(), nullable=False
    )
    op.drop_column("companies", "data_quality_flags")
    op.drop_column("companies", "ingested_at")
    op.drop_column("companies", "source_record_id")
    op.drop_column("companies", "source_system")
    op.drop_column("companies", "postal_code")
    op.drop_column("companies", "postal_address")
    op.drop_column("companies", "physical_address")
    op.drop_column("companies", "contact_email")
    op.drop_column("companies", "egp_registration_number")
    op.drop_column("companies", "brs_number")
    op.drop_column("companies", "supplier_type")
    op.drop_index("ix_contracts_tender", table_name="contracts")
    op.drop_index("ix_contracts_source", table_name="contracts")
    op.drop_index("ix_contracts_company", table_name="contracts")
    op.drop_table("contracts")
    op.drop_index("ix_ownership_name", table_name="ownership_records")
    op.drop_index("ix_ownership_company", table_name="ownership_records")
    op.drop_table("ownership_records")
    # ### end Alembic commands ###
