"""add_case_management_tables

Revision ID: 82a4d92f63d4
Revises: 91ffc3a6b4bc
Create Date: 2026-02-07 15:00:45.622137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a4d92f63d4'
down_revision: Union[str, Sequence[str], None] = '91ffc3a6b4bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("priority IN ('HIGH', 'MEDIUM', 'LOW')", name='ck_case_priority'),
    sa.CheckConstraint("status IN ('OPEN', 'INVESTIGATING', 'ESCALATED', 'RESOLVED', 'DISMISSED')", name='ck_case_status'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cases_status', 'cases', ['status'], unique=False)
    op.create_index('ix_cases_tender', 'cases', ['tender_id'], unique=False)
    op.create_table('case_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("note_type IN ('OBSERVATION', 'EVIDENCE', 'DECISION', 'ACTION')", name='ck_note_type'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notes_case', 'case_notes', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notes_case', table_name='case_notes')
    op.drop_table('case_notes')
    op.drop_index('ix_cases_tender', table_name='cases')
    op.drop_index('ix_cases_status', table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
