"""initial_schema

Revision ID: 91ffc3a6b4bc
Revises: 
Create Date: 2026-02-07 00:19:24.579611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91ffc3a6b4bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_created', 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('directors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('officials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_directors',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('director_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['director_id'], ['directors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'director_id')
    )
    op.create_table('official_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('official_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['official_id'], ['officials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['directors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('official_id', 'person_id', name='uq_official_person')
    )
    op.create_table('tenders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('procuring_entity', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.Column('awarded_amount', sa.Float(), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('awarded_to', sa.UUID(), nullable=True),
    sa.Column('procurement_officer_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('estimated_value >= 0', name='ck_positive_estimated_value'),
    sa.ForeignKeyConstraint(['awarded_to'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['procurement_officer_id'], ['officials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    op.create_index('ix_tenders_category', 'tenders', ['category'], unique=False)
    op.create_index('ix_tenders_status', 'tenders', ['status'], unique=False)
    op.create_table('bids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('submission_date', sa.DateTime(), nullable=False),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_id', 'company_id', name='uq_bid_tender_company')
    )
    op.create_index('ix_bids_tender', 'bids', ['tender_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.Column('rule_factors', sa.JSON(), nullable=True),
    sa.Column('ml_anomaly_score', sa.Float(), nullable=True),
    sa.Column('ml_feature_importance', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('overall_score >= 0 AND overall_score <= 100', name='ck_score_range'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_tender', 'risk_assessments', ['tender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_risk_tender', table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index('ix_bids_tender', table_name='bids')
    op.drop_table('bids')
    op.drop_index('ix_tenders_status', table_name='tenders')
    op.drop_index('ix_tenders_category', table_name='tenders')
    op.drop_table('tenders')
    op.drop_table('official_relationships')
    op.drop_table('company_directors')
    op.drop_table('officials')
    op.drop_table('directors')
    op.drop_table('companies')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_index('ix_audit_created', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
